// Generated by CoffeeScript 1.12.7
var main, proxy;

proxy = function(fn) {
  var script;
  script = document.createElement('script');
  script.textContent = '(' + fn.toString() + ')(window);';
  return document.body.appendChild(script);
};

main = function() {
  var btn, iconPreview, saveSVG;
  iconPreview = document.querySelector('.icon-workspace .download-icon');
  if (!iconPreview) {
    return;
  }
  saveSVG = function() {
    var dom, filename, svgWrapper, text;
    svgWrapper = document.querySelector('.icon.transparent-background>div');
    if (!svgWrapper) {
      return;
    }
    text = encodeURIComponent(svgWrapper.innerHTML);
    filename = document.querySelector('.icon-workspace .title').textContent.trim() + '.svg';
    dom = document.createElement('a');
    dom.setAttribute('href', 'data:text/plain;charset=utf-8,' + text);
    dom.setAttribute('download', filename);
    return dom.click();
  };
  btn = document.createElement('div');
  btn.className = 'button';
  btn.style.textAlign = 'center';
  btn.style.width = '100%';
  btn.style.backgroundColor = 'green';
  btn.style.borderColor = '#efeaea';
  btn.style.marginTop = '10px';
  btn.textContent = 'Download SVG';
  btn.onclick = saveSVG;
  return iconPreview.appendChild(btn);
};

proxy(main);
